### ISSUE TITLE
ruby-runtime version dep breaks rbenv in 1.6

### ISSUE THREAD

**Issue by jmif** [jenkinsci/rbenv-plugin#36]

**Comment by stadia** [comment]
unfortunately ruby-runtime plugin broken down.

```
Failed Loading plugin ruby-runtime
java.io.IOException: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:441)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:384)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$8.runTask(Jenkins.java:915)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jruby.util.collections.WeakHashSet
	at org.kohsuke.asm5.ClassWriter.getCommonSuperClass(ClassWriter.java:1684)
	at org.kohsuke.asm5.ClassWriter.getMergedType(ClassWriter.java:1654)
	at org.kohsuke.asm5.Frame.merge(Frame.java:1426)
	at org.kohsuke.asm5.Frame.merge(Frame.java:1325)
	at org.kohsuke.asm5.MethodWriter.visitMaxs(MethodWriter.java:1475)
	at org.kohsuke.asm5.tree.MethodNode.accept(MethodNode.java:833)
	at org.kohsuke.asm5.commons.JSRInlinerAdapter.visitEnd(JSRInlinerAdapter.java:187)
	at org.kohsuke.asm5.MethodVisitor.visitEnd(MethodVisitor.java:877)
	at org.kohsuke.asm5.ClassReader.readMethod(ClassReader.java:1021)
	at org.kohsuke.asm5.ClassReader.accept(ClassReader.java:693)
	at org.kohsuke.asm5.ClassReader.accept(ClassReader.java:506)
	at org.jenkinsci.bytecode.Transformer.transform(Transformer.java:76)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:800)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jenkinsci.jruby.RubyClassConverter.<init>(RubyClassConverter.java:12)
	at org.jenkinsci.jruby.JRubyXStream.register(JRubyXStream.java:25)
	at ruby.RubyRuntimePlugin.initRubyXStreams(RubyRuntimePlugin.java:44)
	at ruby.RubyRuntimePlugin.start(RubyRuntimePlugin.java:28)
	at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:449)
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:438)
	... 9 more
```
